apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git://git-mirror.gitops.svc.cluster.local/agent.git
    targetRevision: HEAD
    path: chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: agent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
